### ISSUE TITLE
Build error in Arch Linux

### ISSUE THREAD

**Issue by zxp19821005** [Temtem-Interactive-Map/Temzone-Desktop#15]
### Basic info
OS : EndeavourOS x86_64 6.1.34-1-lts
DE : Cinnamon 5.8.1
Other:
- node v20.3.0
- npm 8.19.2
- source : [1.0.3](https://github.com/Temtem-Interactive-Map/Temzone-Desktop/archive/refs/tags/0.1.3.tar.gz)

### npm install
```
$ npm install

> temzone@0.1.3 postinstall
> electron-builder install-app-deps

  • electron-builder  version=24.4.0
  • loaded configuration  file=/home/zxp-endeavouros/.cache/paru/clone/Temzone-Desktop-0.1.3/electron-builder.yml
  • executing @electron/rebuild  arch=x64 version=21.3.3 appDir=/home/zxp-endeavouros/.cache/paru/clone/Temzone-Desktop-0.1.3

added 354 packages, removed 154 packages, and changed 221 packages in 8s

199 packages are looking for funding
  run `npm fund` for details
```
### npm run build:linux
```
$ npm run build:linux

> temzone@0.1.3 build:linux
> nextron build --linux

[nextron] Clearing previous builds
[nextron] Building renderer process
- info Linting and checking validity of types  
- info Creating an optimized production build .
(process:57300): VIPS-WARNING **: 10:17:39.674: unable to load "/usr/lib/vips-modules-8.14/vips-openslide.so" -- libopenslide.so.0: cannot open shared object file: No such file or directory
- info Creating an optimized production build ..vips_image_dispose: temp-73 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-63 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-64 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-54 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-230 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-233 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-250 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-256 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-347 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-370 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-390 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-397 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-487 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-512 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-510 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-541 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-627 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-643 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-664 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-660 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-754 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-769 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-805 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-839 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-878 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-912 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-956 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-941 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1021 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1037 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1087 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1094 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1154 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1190 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1224 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1226 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1284 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1325 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1381 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1380 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1372 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1460 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1514 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1523 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1522 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1594 vips_shrinkv_gen computed 387%
- info Creating an optimized production build ...vips_image_dispose: temp-1642 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1675 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1678 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1679 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1766 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1810 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1824 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1811 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1902 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1925 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1965 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-1972 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2062 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2065 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2069 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2118 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2178 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2217 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2241 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2268 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2278 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2342 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2385 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2396 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2435 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2474 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2516 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2576 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2585 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2573 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2608 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2714 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2716 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2731 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2736 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2833 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2839 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2894 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2917 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2953 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-2954 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3033 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3038 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3101 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3106 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3153 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3190 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3250 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3251 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3283 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3282 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3365 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3396 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3424 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3442 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3498 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3532 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3600 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3612 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3613 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3605 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3723 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3737 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3734 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3836 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3835 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3857 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3855 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3959 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-3958 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-4022 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-4023 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-4078 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-4125 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-4151 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-4152 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-4219 vips_shrinkv_gen computed 387%
vips_image_dispose: temp-4226 vips_shrinkv_gen computed 387%
- info Creating an optimized production build  
- info Compiled successfully
- info Collecting page data ...FirebaseError: Firebase: Error (auth/invalid-api-key).
    at createErrorInternal (file:///home/zxp-endeavouros/.cache/paru/clone/Temzone-Desktop-0.1.3/node_modules/@firebase/auth/dist/node-esm/totp-e47c784e.js:490:40)
    at _assert (file:///home/zxp-endeavouros/.cache/paru/clone/Temzone-Desktop-0.1.3/node_modules/@firebase/auth/dist/node-esm/totp-e47c784e.js:494:15)
    at Component.instanceFactory (file:///home/zxp-endeavouros/.cache/paru/clone/Temzone-Desktop-0.1.3/node_modules/@firebase/auth/dist/node-esm/totp-e47c784e.js:6506:9)
    at Provider.getOrInitializeService (file:///home/zxp-endeavouros/.cache/paru/clone/Temzone-Desktop-0.1.3/node_modules/@firebase/component/dist/esm/index.esm2017.js:290:39)
    at Provider.initialize (file:///home/zxp-endeavouros/.cache/paru/clone/Temzone-Desktop-0.1.3/node_modules/@firebase/component/dist/esm/index.esm2017.js:234:31)
    at initializeAuth (file:///home/zxp-endeavouros/.cache/paru/clone/Temzone-Desktop-0.1.3/node_modules/@firebase/auth/dist/node-esm/totp-e47c784e.js:2943:27)
    at getAuth (file:///home/zxp-endeavouros/.cache/paru/clone/Temzone-Desktop-0.1.3/node_modules/@firebase/auth/dist/node-esm/totp-e47c784e.js:6567:18)
    at /home/zxp-endeavouros/.cache/paru/clone/Temzone-Desktop-0.1.3/renderer/.next/server/pages/login.js:491:68 {
  code: 'auth/invalid-api-key',
  customData: { appName: '[DEFAULT]' }
}

> Build error occurred
Error: Failed to collect page data for /login
    at /home/zxp-endeavouros/.cache/paru/clone/Temzone-Desktop-0.1.3/node_modules/next/dist/build/utils.js:1155:15 {
  type: 'Error'
}
- info Collecting page data .

Cannot build electron packages:
Error: Command failed with exit code 1: next build /home/zxp-endeavouros/.cache/paru/clone/Temzone-Desktop-0.1.3/renderer
```

**Comment by TheLokin** [comment]
Currently, the project is primarily focused on compatibility with Windows platforms, although deployables can be generated for other operating systems such as Linux and Mac. However, the error you are experiencing does not appear to be related to the Linux environment it is running on, but rather to an incorrect configuration.

This project uses Firebase for user authentication, so it is necessary to create a [Firebase project](https://firebase.google.com) and provide the necessary variables for proper validation. For more information, please refer to the [README](https://github.com/Temtem-Interactive-Map/Temzone-Desktop/blob/main/README.md) file in the repository.

Additionally, this application employs a backend to handle all requests. Therefore, it is also necessary to have an instance of the backend up and running. You can find the source code of the backend in the following repository: [link to the backend repository](https://github.com/Temtem-Interactive-Map/Temzone-API). Be sure to read the [README](https://github.com/Temtem-Interactive-Map/Temzone-API/blob/main/README.md) to properly configure the backend and provide the necessary configuration for its correct operation.
